var express = require('express');
var router = express.Router();
// const auth = require('/middleware/auth.middleware.api');
const auth = require('../middleware/middleware');
const customer = require('../controller/customer_controller');
const upload = require("../middleware/upload");
router.get('/',auth.LoginRequire,customer.getList);
router.post('/',auth.LoginRequire,customer.postSearch);
router.get('/get-all',customer.getAll);
router.post('/reg',customer.postRegisterCustomer);
router.post('/login',customer.postLoginCustomer);
router.post('/logout',customer.postLogOut);
router.post('/update',upload.single('image'),customer.postUpdateCustomer);
router.post('/profile',customer.getProfile);
router.post('/repass',customer.postRePassword);
router.post('/forgot-pass',customer.postForgotPass);
router.post('/sendsms',customer.sendCodeVerify);
router.put('/banacc/:id',customer.setStatus);
module.exports = router;